# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "affd4e7a2013c1bdff7ae8fad1e5885d"
name = "ap-remix-app"
handle = "ap-remix-app"
application_url = "https://wells-paintball-registry-title.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wells-paintball-registry-title.trycloudflare.com/auth/callback",
  "https://wells-paintball-registry-title.trycloudflare.com/auth/shopify/callback",
  "https://wells-paintball-registry-title.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
